### ISSUE TITLE
Wings not interactable when in survival.

### ISSUE THREAD

**Issue by Zalycon** [CammiePone/Icarus#1]
I cannot fly with the wings and putting them into the cape slot does nothing to fix this.
Heres my mod list: 
All my mods should be fabric expect one
YUNGS Better caves 
Better-end 
Better-nether
byg
cloth-api
fabric-api
geckolib-fabric
guardians-galore
icarus-1.2
Origins-1.16.5-0.7.3
Origins-Classes-1.16.5-1.1.1
Requiem-1.7.7
RoughlyEnoughItems-5.11.218
TooManyOrigins-1.1.6.5-0.13
Trinkets-2.6.7
Xaeros_Minimap_21.8.2 (Forge)
YungsApi-1.16.5-Fabric-5

As for my output log/file log:
Warns:
08:34:46.896
Non-Fabric mod JAR at "C:\Users\Admin\AppData\Roaming\.minecraft\mods\Xaeros_Minimap_21.8.2_Forge_1.16.5.jar", ignoring
08:34:46.928
The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
08:34:46.929
The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
08:35:31.805
Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
08:35:31.806
Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
08:35:31.808
Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
08:35:31.809
Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
08:35:31.810
Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
08:35:40.218
Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
08:35:40.219
Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
08:35:40.220
Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
08:35:40.220
Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
08:35:40.221
Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9,

Errors:
08:35:04.491
No data fixer registered for byg:boat
There were no fatals.

As for the rest of the info, it's too big to copy down and paste here.
I hope with this information you can find the issue.

**Comment by CammiePone** [comment]
I will probably need the other information, but I would like you to try disabling Requiem and TooManyOrigins and see if that changes anything. Those are the only two in your modlist that have a chance to be making it not work as far as I can think.

**Comment by CammiePone** [comment]
OH! Question, you wouldn't happen to be using an origin that isn't human, or possessing something when trying to use the wings, would you? I should've asked that first but that may be what's breaking it in survival.

**Comment by CammiePone** [comment]
So I just installed all the same mods that you have, but it's working fine for me? Is there another mod you're leaving out, like Optifine, or maybe you're activating the wings wrong? Or maybe you don't have any hunger and that's why it's not working?

**Comment by Zalycon** [comment]
> So I just installed all the same mods that you have, but it's working fine for me? Is there another mod you're leaving out, like Optifine, or maybe you're activating the wings wrong? Or maybe you don't have any hunger and that's why it's not working?

No that is all the mods I have installed currently. My hunger was full when using them and if I'm correct it's double jump/R to activate them. No idea what is causing it since they seem to become invalid when I re-equip them after already putting them on.

**Comment by CammiePone** [comment]
That's... even more bizarre because they all use the same logic. Like, literally. They all use the exact same class.

**Comment by CammiePone** [comment]
Oh, also. R itself shouldn't be a requirement. It's just spacebar, like an elytra, and holding W to give yourself the speed. R is just my sprint key.

**Comment by CammiePone** [comment]
Yeah, just tried every set of wings. They all work the same with the list of mods you've given me. I'm not sure what the problem is :/

**Comment by Zalycon** [comment]
> Yeah, just tried every set of wings. They all work the same with the list of mods you've given me. I'm not sure what the problem is :/
> 
> Does it still happen with just Icarus installed?

Seems like it does. I used the gray and black dragon wings when testing but other than that I have no idea whats causing the issue.

**Comment by CammiePone** [comment]
> Seems like it does. I used the gray and black dragon wings when testing but other than that I have no idea whats causing the issue.

Then I have no idea what the issue is. I'm not getting this at all when I test it myself, and the logs aren't showing anything weird.
