### ISSUE TITLE
Camera Overhaul Reforged Compat

### ISSUE THREAD

**Issue by AvacadoWizard120** [CammiePone/Icarus#101]
I just got a comment on my project Camera Overhaul Reforged:

> Hello!! I'm getting this error whilst playing with Icarus mod.
>
>
>
> [12:11:49] [Render thread/ERROR]: Unreported exception thrown!
>
> java.lang.AbstractMethodError: Receiver class dev.cammiescorner.icarus.neoforge.compat.CameraOverhaulCompat does not define or > inherit an implementation of the resolved method 'abstract void OnCameraUpdate(net.minecraft.world.entity.Entity, net.minecraft.client.Camera, mirsario.cameraoverhaul.core.structures.Transform, float)' of interface > mirsario.cameraoverhaul.core.callbacks.CameraUpdateCallback.
>
> 	at mirsario.cameraoverhaul.core.callbacks.CameraUpdateCallback.lambda$static$0(CameraUpdateCallback.java:13) ~[cameraoverhaul-1.1-1.20.4.jar%23517!/:1.1-1.20.4]
>
>
>
> I disabled Icarus and I was able to create a new world.

If you have time, it would be sweet to work together and resolve this issue. All I really did to port the mod from fabric to neoforge was copy mirsario's code, so it's pretty darn similar I just don't use abstractions.

**Comment by AvacadoWizard120** [comment]
It's because of a bug in spectator mode in the Camera Overhaul mod that required some changes to how the mod target's the player's camera. I can submit a pull request to fix this issue if you would like.

**Comment by AvacadoWizard120** [comment]
```java
// CameraOverhaulCompat

@Override
public void OnCameraUpdate(Entity focusedEntity, Camera camera, Transform cameraTransform, float deltaTime) {
    // ...
}
```


somethin like that

**Comment by UpcraftLP** [comment]
I'll fix it, but please stop making breaking API changes in minor releases...

**Comment by AvacadoWizard120** [comment]
> I'll fix it, but please stop making breaking API changes in minor releases...

I was fixing a bug 🤷‍♂️ it wasn't anything that changed the mod really it was just a patch. Hence the minor release.
