### ISSUE TITLE
Enchantments not applied Via give command

### ISSUE THREAD

**Issue by mmiinnaa11** [CammiePone/Icarus#103]
When we tried to give ourselves wings with any enchantment, we only receive the wing without the enchantments
But we apply it with an anvil, Is this a bug or do we need to use a work around command?
![image](https://github.com/Up-Mods/Icarus/assets/173669792/bc2a2ccd-cf26-45a9-bba3-8d04f5a749c6)
![image](https://github.com/Up-Mods/Icarus/assets/173669792/4c58c809-0ac4-497f-988b-627d1eb795c5)

**Comment by UpcraftLP** [comment]
Your command seems to be wrong.

Try something like `/give @s icarus:black_dragon_wings{Enchantments:[{lvl:1,id:vanishing_curse}]}`
