### ISSUE TITLE
I want turn off the visibillity of the wing but it not working

### ISSUE THREAD

**Issue by FatalFreeze** [CammiePone/Icarus#104]
I really like this mod I hope it can customize the size, visibility, and location of the wings, and then it can better work with customizable player model mod, or it can add an invisible wing!

**Comment by UpcraftLP** [comment]
You can use the [Figura](https://figuramc.org) mod to hide/reposition/scale the wings, as explained in the [wiki](https://mods.upcraft.dev/wiki/books/icarus/page/figura).
