### ISSUE TITLE
Please add 1.19.4 

### ISSUE THREAD

**Issue by CryoNine** [CammiePone/Icarus#105]
I tried everything possible to make 1.19.3 work but it seems entirely dependent on just that version. Managed to get Minecraft to start up, but it crashes as soon as I join a world.

I would really like to have a wings mod and this is the only updated fabric mod I could find for just that, and it's such a cool mod. 

My survival world has 400 mods and a great many of them only have up to 1.19.4, and the only thing it needs now is wings.

**Comment by UpcraftLP** [comment]
Done!

**Comment by CryoNine** [comment]
> Done!:

:D
