### ISSUE TITLE
[1.20.1] Light Blue Mechanical Leather Wings use wrong item texture

### ISSUE THREAD

**Issue by java-jambalaya** [CammiePone/Icarus#108]
This is like the most specific nitpick ever but `light_blue_mechanical_leather_wings` wrongly uses the item texture for the `light_blue_mechanical_feathered_wings` and I can't live on knowing this exists without letting the world know. Just needs the model file for the leather wings updating to reference the correct texture. My priorities in life are staggering.

**Comment by UpcraftLP** [comment]
Thanks for catching that, seems I accidentally copied the wrong file there when fixing all the asset files
