### ISSUE TITLE
A Suggestion

### ISSUE THREAD

**Issue by KaiTheGai** [CammiePone/Icarus#109]
I think it would be cool to have the wings fold in a bit more when not in use. 
![c161d1c1a907de9ae6f84f3c13ee359c](https://github.com/user-attachments/assets/b199f370-08f9-4018-a890-ed800b89d239)

**Comment by UpcraftLP** [comment]
definitely planned at some point, but for now I'm first focusing on getting the mod updated to MC 1.21.

Gonna close this issue tho as the feature has already been suggested in #41
