### ISSUE TITLE
it doesnt work for me

### ISSUE THREAD

**Issue by lapis046** [CammiePone/Icarus#11]
i have tried using it but everytime the animation stops and i cant fly

**Comment by wackoamd1** [comment]
finaly got a elytra turned it into wings only to find it doesnt fly , great nice bug 1.18.1 icarus 1.9

**Comment by CammiePone** [comment]
Very cool reports, but what mods do you have installed, do you have full hunger, etc because the information you've given me is literally useless

**Comment by wackoamd1** [comment]
i even tried it in creative , so without any hunger and in survival with full health.
u can wear the wings , but it doesnt do anything . i even installed elytra in trinket slot mod to see if maybe it was the trinketslot that didnt work , and everything is fine wiith a normal elytra in the cape slot.
fabric 1.12.2 mc 1.18.1 .  
it doesnt throw an error , u just cant rightclick a firework rocket. (it doesnt even make the animation of rightclick) 
somehow the firework blocks or doesnt "see" your wings. thats the best i can explain it , hope it helps cause it doesnt crash or error or anything.

**Comment by CammiePone** [comment]
...you don't use fireworks with the wings. you just hold W
