### ISSUE TITLE
Exit Code-1

### ISSUE THREAD

**Issue by SCP-5106** [CammiePone/Icarus#113]
I've been trying to get Icarus working for about three hours, but it always crashes the same way. And I even turned off the other mods but still the same thing.

Here is the crash report:
[crash-2024-08-19_20.18.44-client.txt](https://github.com/user-attachments/files/16667137/crash-2024-08-19_20.18.44-client.txt)

**Comment by UpcraftLP** [comment]
Hello, it seems like you have the wrong version of the Common Network API. You have 1.0.5-1.20.1 (which is for Minecraft 1.20.1) but are playing Minecraft 1.21

**Comment by SCP-5106** [comment]
I'll see if that fixes it.

**Comment by SCP-5106** [comment]
I was checking and they don't have a 1.21.1 version which just means I'l have to use a different version which is fine

**Comment by SCP-5106** [comment]
It did
