### ISSUE TITLE
Registry Object Not Found crash in Multiplayer

### ISSUE THREAD

**Issue by Abvieon** [CammiePone/Icarus#115]
In a multiplayer server, when I attempt to open the creative menu with Icarus installed, the game crashes with the following error:

Description: Unexpected error

java.lang.NullPointerException: Registry Object not present: icarus:white_feathered_wings
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:572) ~[forge-1.20.1-47.3.0-universal.jar%23573!/:?] 

None of the Icarus items are present in the Just Enough Items menu in multiplayer either. However they are present and work fine in singleplayer.

**Comment by UpcraftLP** [comment]
Hello o/

What crashes, the server or the client?
and could you send a full log please?
