### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Kirims1** [CammiePone/Icarus#118]
I recently added the Icarus mod to All of Fabric 3, but when I try to use it, I have to spam the space button in order for it work. Also, the flight animation isn't working. Any ideas why this is happening?

**Comment by CammiePone** [comment]
im guessing this is a duplicate of #29 and #64? thing is, a fix for what would be among the first versions of Icarus is unlikely to be released. 1.16 is legacy at this point and isn't going to receive bug fixes, sorry
