### ISSUE TITLE
Make a wing slot so you can wear wings and a cape at the same time

### ISSUE THREAD

**Issue by MoonSkul** [CammiePone/Icarus#12]
This is just a suggestion because I thought that it would be nice if the wings get their own slot instead of taking up the cape slot of the trinkets mod.

**Comment by CammiePone** [comment]
You can do it yourself with a datapack. There isnt much reason for me to add it really

**Comment by MoonSkul** [comment]
alright, didn't know I could do that myself. Have a nice day!
