### ISSUE TITLE
Icarus 2.10.0 Crash with Figura 0.1.2 [1.20.1 Quilt]

### ISSUE THREAD

**Issue by Xiribidus** [CammiePone/Icarus#124]
Trying to launch the game with both mods enabled crashes, disabling either (while leaving the dependencies enabled) fixes this.
Isolated launch attempt:

https://mclo.gs/TR9hDEY

Mods and dependencies updated to latest viable version according to Modrinth launcher.

**Comment by Xiribidus** [comment]
"[...] in the latest rcs figura changed how it lets other mods mixin to it and icarus hasn’t updated to reflect that, it’s still on the old version of mixin-ing which now leads to this" - someone in the Figura discord

**Comment by UpcraftLP** [comment]
> "[...] in the latest rcs figura changed how it lets other mods mixin to it and icarus hasn’t updated to reflect that, it’s still on the old version of mixin-ing which now leads to this" - someone in the Figura discord

entirely unrelated to your issue.

**Comment by UpcraftLP** [comment]
You are using figura 0.1.2, instead of the latest version (0.1.4). Updating figura will fix your issue.
