### ISSUE TITLE
Icarus Origin Gamebreaking On Servers

### ISSUE THREAD

**Issue by Aridastle** [CammiePone/Icarus#14]
Hello, I have a modpack and server that has icarus: https://www.curseforge.com/minecraft/modpacks/arid-castle . There is a game breaking glitch with the icarus origin. Players on a server can change the icarus config clientside and can essentially use the origin as a hacked client. For example, turning the icarus speed to crazy high settings. I do not think this is intended, so I am hoping this can be fixed as I like the mod a lot.

**Comment by CammiePone** [comment]
That is definitely not intended. I can try and fix it at some point but classes just started back up for me so I'm now busy

**Comment by Aridastle** [comment]
If it is easier, just an option to remove the origin icarae would be appreciated.

**Comment by CammiePone** [comment]
You can do that with datapacks already. That wouldnt solve the underlying problem, though. This will affect the wings as well

**Comment by Aridastle** [comment]
Oof, sorry to hear that. Does not sound fun to fix.
