### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by wackoamd1** [CammiePone/Icarus#15]
again i tried icarus and again it doesnt work nothing happens when equiped
even barebones modded with 
fabric 1.12.2
architectury 3.4.9
clothconfig 6.1.48
fabric api 0.45.2
icarus 1.9
rei 7.1.361
trinkets 3.1.0
nothing happens  , in f5 mode u can see the wings briefly blink like they want to open but nothing happens not in survival not in creative ( well.. double jumping puts u in creative flight)
i have no idea , no error no nothing in the log , not on single player , not on server. i dont know why it doesnt work

**Comment by CammiePone** [comment]
Put the wings on, leave the game, and re-enter and tell me if they're still on. Trinkets may be doing its garbage desync stuff

**Comment by wackoamd1** [comment]
i just took out everything trinkets related  ;_) and reinstalled them now it works ;-)
