### ISSUE TITLE
issue with world generation???

### ISSUE THREAD

**Issue by DilerFlora** [CammiePone/Icarus#22]
hi! so i've have played this mod before with some other mods and nothing was breaking [1.16.5]
but yesterday when i wanted to play just this mod again its just not loading chunks when i try to create a new world
and its not crashing minecraft but just stop working
is there any fixing for this??

**Comment by CammiePone** [comment]
It's not world gen, because I literally don't touch it. You can't break things you don't mess with.

It's most likely something to do with player data being fucked, and if that's the case, no, there's nothing you can do except update to a supported version of the mod.
