### ISSUE TITLE
Issue with removing recipe for 1 pair of wings

### ISSUE THREAD

**Issue by TheMightyMcGrew** [CammiePone/Icarus#28]
Using craftTweaker to remove and rewrite recipes, every other pair of wings in the game removes and re-writes perfectly except for the icarus:black_dragon_wings. It simply does not care, wont remove, wont allow for rewrite. Is the item tag different than what it says it is? or is this something I need to take to CT?

**Comment by CammiePone** [comment]
you may have done something wrong if just that one doesnt work, since it doesnt use any tags that no other recipe uses

also, not to sound rude, but why use crafttweaker for recipes? its kinda redundant these days

**Comment by TheMightyMcGrew** [comment]
because i run a server where certain items need to be gated for various reasons. How is it redundant?
and no im copying directly with /ct hand, pasting in, i even just edited "black" to "white" in the item: line and the white pair were then disabled

**Comment by TheMightyMcGrew** [comment]
> you may have done something wrong if just that one doesnt work, since it doesnt use any tags that no other recipe uses
> 
> also, not to sound rude, but why use crafttweaker for recipes? its kinda redundant these days

also if crafttweaker is redundant, point me in the direction of something more relevant please

**Comment by ardissaps** [comment]
> > you may have done something wrong if just that one doesnt work, since it doesnt use any tags that no other recipe uses
> > also, not to sound rude, but why use crafttweaker for recipes? its kinda redundant these days
> 
> also if crafttweaker is redundant, point me in the direction of something more relevant please

kubejs, or simply datapack
