### ISSUE TITLE
doesnt work (without origin)

### ISSUE THREAD

**Issue by FATPUCKINGIDIOT** [CammiePone/Icarus#29]
for the new 1.19 version, in either creative or survival, the wings dont work. unless you use the origins mod, everytime i try to use them, i can see my character sort of "glitches" out for a quick second but then nothing happens. ive tried to remove possibly conflicting mods but nothing has seemed to work just yet. is it supposed to be intentional that it only works for the singular origin? or is there a config setting i need to find?

https://user-images.githubusercontent.com/108600460/177023307-462f680c-c1e4-4c4c-a25a-e8fb187046a4.mp4

**Comment by CammiePone** [comment]
that's really bizarre. should work without origins. ill look into it tomorrow, its after midnight for me rn

**Comment by chronosacaria** [comment]
I wonder if I screwed something up when I updated it? If I did, I apologise. I was about to come a check if something had been posted about this issue ._.

**Comment by FATPUCKINGIDIOT** [comment]
its all good man stuff happens

**Comment by Unpowerful1** [comment]
Has this been figured out? if so what do i need to do?

**Comment by chronosacaria** [comment]
@CammiePone I found the issue! It looks like when the default value of the wings is set to `0` (https://github.com/CammiePone/Icarus/commit/afa689261aebb4f2244e3540cf8ce398fa8e7abc), the wings are, functionally, broken as per the `WingItem#isUsable` boolean. If the default value is set above `0`, the issue appears to be solved

**Comment by CammiePone** [comment]
ah I can fix that then

**Comment by JedGITH** [comment]
If in creative, change to survival and eat something to remove hunger, and then go back into creative should fix your issue. If you have this issue with full hunger and in survival than different story.
