### ISSUE TITLE
Changing Settings Client Side on Servers

### ISSUE THREAD

**Issue by AuhsojR** [CammiePone/Icarus#32]
Players using the mod on server can just change settings client side and it works. This gives some players advantages. Is there a way to disable this?

**Comment by CammiePone** [comment]
its a known issue, it's just cbt to go about doing. i may try and see if I can reset the client config to match the server if someone ever tries to change it, but that could lead to packet spam

**Comment by AuhsojR** [comment]
Ok, thank your for your response.

**Comment by CammiePone** [comment]
no need to close it, its an issue that needs to be solved and I really should just do it

**Comment by AuhsojR** [comment]
wait how do I open it'

**Comment by AuhsojR** [comment]
nvm

**Comment by AuhsojR** [comment]
I just realised I re-closed it when you opened it. Im sorry im such an idiot.

**Comment by CammiePone** [comment]
hehehe nw, have a good night ^-^

**Comment by AuhsojR** [comment]
Thank you, and you too.

**Comment by CammiePone** [comment]
this is finally fixed, only took me almost a year
