### ISSUE TITLE
Alternate idle wing pose + invis for icarae origin

### ISSUE THREAD

**Issue by madcaker** [CammiePone/Icarus#33]
It would probably look a bit better if the wings where closer in and folded up like you would see with birds retracting their wings. If I could get a model of the wings maybe I could play around with it and show what I mean. 

I've also had issues with the wings being visible while under the effects of invisibility. And since icarae have no way of taking off their wings it effectively makes invisibility useless.

**Comment by UpcraftLP** [comment]
#41
