### ISSUE TITLE
Wings keep dissapearing

### ISSUE THREAD

**Issue by 03koopa** [CammiePone/Icarus#34]
Everytime anyone on my server interacts with just there inventory their wings will dissapear both visually and physcially and will not be able to fly. If they leave the game and come back the wings will return to their back. The only way to take the wings off is to die with Keep Inventory off. This all only happens in the players inventory where you can equip armor also when on the ground and not flying.

**Comment by CammiePone** [comment]
sounds like a trinkets issue 'cause that's what handles all inventory related stuff
