### ISSUE TITLE
Internal Server Error player crash

### ISSUE THREAD

**Issue by V-lpen** [CammiePone/Icarus#35]
Sometimes when using Icarus wings, it will cause a player to crash. I have no idea why but this also effects the 1.18.2 version of this mod. The log is 
https://mcpaste.io/824645938b0e56a4

There is no useful crash logs on client, only server.

Icarus v1.13
Minecraft 1.19
Trinkets-3.4.0
Fabric API-0.58.0+1.19
Fabric Loader version 0.14.9

**Comment by suerion** [comment]
Hey, we had the same error on 1.19.2 https://pastebin.com/Tye1vZVj

**Comment by UpcraftLP** [comment]
Fixed in the next release, but wont be backported to 1.19.x.

**Comment by V-lpen** [comment]
Oh my god, ive been coping with this bug for years, still using icarus despite being crashed every few times i took off in flight. Thank you SO much upcraft!
