### ISSUE TITLE
Armor Stand Compatibility

### ISSUE THREAD

**Issue by LadyOf3Heavens** [CammiePone/Icarus#36]
Once changed from elytra to icarus wings they are no longer able to be displayed on an armor stand, it would be nice to be able to display the wing selections.

**Comment by CammiePone** [comment]
this would be better sent to Trinkets, as Icarus uses it for the slot the wings go in.

**Comment by LadyOf3Heavens** [comment]
The better end mod I play with also adds new elytra that go in the trinkets slot and they display on the armor stand just fine though.

**Comment by CammiePone** [comment]
That's because they add an actual elytra that can also go in the chest slot. Icarus' wings can only be put in the Trinket slot.
