### ISSUE TITLE
More Origins Compatability

### ISSUE THREAD

**Issue by NixityNull** [CammiePone/Icarus#4]
Is it possible to maybe add the ability to add specific kinds of permawings to specific origins via datapack, similar to the mermod?

**Comment by CammiePone** [comment]
Yes it is doable, but I'm _probably_ not going to do it. I'll keep it in the back pocket tho

**Comment by sableseyler** [comment]
Is there a way to manually swap it through command abuse?

**Comment by sableseyler** [comment]
Better question, are you open to a three sentence write-up of *how* you'd do it if you did, and would you accept a pull request?

**Comment by CammiePone** [comment]
I would just make it a cosmetic power where you put the item id of the wings you want

**Comment by sableseyler** [comment]
That makes sense. Thank you!

**Comment by suuty** [comment]
could u make it so that we can chose what armour slows u down when flying

**Comment by Merith-TK** [comment]
I definately would like to have a "origins power" based, config for which set of wings it has by default,

**Comment by NixityNull** [comment]
It's me again, just wondering what code you used to add the wings to the icarae origin, because the .json file for the wings power has literally only one line of code.

**Comment by CammiePone** [comment]
> It's me again, just wondering what code you used to add the wings to the icarae origin, because the .json file for the wings power has literally only one line of code.

Java. The power json is just a dummy json.

> could u make it so that we can chose what armour slows u down when flying

no

**Comment by CammiePone** [comment]
I should also probably update y'all and let you know that it will be happening eventually, just not right now.

**Comment by BioTechproject27** [comment]
> It's me again, just wondering what code you used to add the wings to the icarae origin, because the .json file for the wings power has literally only one line of code.

Ay, kinda new here and want to add icarus wings to my origin. Does the origin you're talking about have those and if so could you please post a link to it? I'm having such a hard time adding those. Since /item replace doesn't work as trinkets isn't a new inventory slot like the others so it doesn't get recognized, I also can't use /data command as one can't modify player data like this. It's just such a pain and I need help.

**Comment by NixityNull** [comment]
> > It's me again, just wondering what code you used to add the wings to the icarae origin, because the .json file for the wings power has literally only one line of code.
> 
> Ay, kinda new here and want to add icarus wings to my origin. Does the origin you're talking about have those and if so could you please post a link to it? I'm having such a hard time adding those. Since /item replace doesn't work as trinkets isn't a new inventory slot like the others so it doesn't get recognized, I also can't use /data command as one can't modify player data like this. It's just such a pain and I need help.

I'm trying to figure it out myself still lol

**Comment by tylerl** [comment]
@NixityNull I've never written Minecraft mods before, and haven't written Java in over a decade. But after spending just 2 hours with the Fabric quick start guide and then reading the source code for this mod, the following stands out:

Origins compatibility is triggered here:

https://github.com/CammiePone/Icarus/blob/3c633051cbd0bc01892c940af91e32583d6be9c5/src/main/java/dev/cammiescorner/icarus/Icarus.java#L25

Which you then cross-reference with this: 

https://github.com/CammiePone/Icarus/blob/3c633051cbd0bc01892c940af91e32583d6be9c5/src/main/java/dev/cammiescorner/icarus/core/integration/IcarusOrigins.java#L13

...which altogether means that `HAS_POWERED_FLIGHT` is false if the Origins mod isn't loaded. And if it is loaded then it's determined by whether your origin has the `icarus:powered_flight` power.

Searching for `HAS_POWERED_FLIGHT` through the rest of the mod shows that there's some reference in the wings rendering code too...

https://github.com/CammiePone/Icarus/blob/3c633051cbd0bc01892c940af91e32583d6be9c5/src/main/java/dev/cammiescorner/icarus/client/renderers/WingsFeatureRenderer.java#L53

Which if I'm reading the code correctly, it looks like we have the powered_flight origin and no wings equipped, then it uses the "feathered_wings" texture.

So it looks like if you want anything different to happen, then you'd need to change the code.

It sounds like CammiePone isn't super interested in implementing whatever you're thinking about at the moment, so fork the repo and implement the feature(s) however you'd like them. You can then send CammiePone a PR and maybe it'll be accepted and maybe it won't. But honestly that part doesn't so much matter. If all you're looking for is to get that feature working, then ta-da, now you have it, and you can play it.

**Comment by CammiePone** [comment]
Just remember you cant distribute it if you do that. I plan to eventually have it be datapackable, but for now it wont be.

I want to focus on Arcanus 2 right now, and that on its own is going to take a long time to do.

**Comment by CammiePone** [comment]
only took me a year, but it's done!

**Comment by Merith-TK** [comment]
Eyyy! Will give it an test "flight"!

**Comment by Merith-TK** [comment]
wait.... a year to the DAY!

**Comment by CammiePone** [comment]
lmao you're right x3
