### ISSUE TITLE
Stopped letting me fly, only glide

### ISSUE THREAD

**Issue by Llama0319** [CammiePone/Icarus#42]
The mod was working fine for about 3 hours, then all of a sudden they stopped letting me actually fly, and only let me glide. I've tried doing /kill, taking all my armor off, getting new wings, trying in creative, and still wont work. And the weird thing is its only in 1 world that they don't work. They are basically elytra now, and I cant figure out how to fix them. If you need me to send a video I can just let me know

Modpack: Medieval MC

**Comment by CammiePone** [comment]
...did you just close an existing issue and then make a new one because i havent had the time to pester you for useable information to figure out why the mod isnt working for you?

**Comment by Llama0319** [comment]
no, i accidentally closed it while trying to comment something

**Comment by TheStrayGuide** [comment]
having this issue as well. wings work like elytra. i still get the flapping animation but i dont gain speed

**Comment by cesperiscool** [comment]
I have been having this issue as well, except I gain speed and have a fuctional flying ability while all other members in my server can only glide. I have had no luck looking for the cause on my end.

**Comment by akselbuch** [comment]
i have a similar issue and it might be related... having high armor value can remove the flight ability of the wings and i am using an rpg mod that dependent on stats can give me a natural armor bonus so i cant fly. is there any way to remove this armor restriction so that this issue doesnt screw me?

**Comment by CammiePone** [comment]
oh yeah, that very well might do it. yeah, its a config option

**Comment by ShieldMaidenVal** [comment]
I'll just bring my issue here instead. I'm on AOF5, and ALL functionality of the mod is gone when it was just before. I put everything on default after editing durability, but it just stopped working. No armor on either.

**Comment by SisterKayby** [comment]
I'm having the same issue. I logged on and didn't have the wings anymore nor could I fly, but I could still glide. I tried reselecting my origin, but that didn't work. I got myself the wings back and tried it with the wings, they do the flapping animation and such, but I still cannot fly.

**Comment by ToasterTeostra** [comment]
So I checked if @akselbuch 's theory was correct, and it is. Armor rating drastically slows your character down. While being able to swoop through the skies with no armor, a full armor bar makes you fall to the ground like a wet sack of wheat (which is a probvlem if you play a warrior-type character with a huge strength stat in the Medieval MC pack).

However, in the config file of the mod, there is the line that says:  "armourSlows": true,". Set it to "False" and you can fly again, even with full armor. In SP, simply change your config. If you have a server, you have to change the file in the server's file manager.

**Comment by JedGITH** [comment]
Check your mod pack, and remove the mod 'do a barrel roll,' this mod changes the normal elytra flight to a more 'realistic' feel, removing it fixes the gliding issue.

**Comment by UpcraftLP** [comment]
@ShieldMaidenVal

**Comment by ItzLucaGER** [comment]
I have a similar issue, after changing the durability to something other than 0 I just cannot fly anymore. I do not have the barrel roll mod installed.

**Comment by UpcraftLP** [comment]
> I have a similar issue, after changing the durability to something other than 0 I just cannot fly anymore. I do not have the barrel roll mod installed.

@ItzLucaGER Could you please open a new issue and include the following information:
- Minecraft Version
- Mod Version
- Steps to reproduce
- Other mods you have installed (if applicable)

**Comment by ItzLucaGER** [comment]
I managed to actually fix it, I think it was just me being stupid. If I change the durability in the config you can't fly until you restart the game, then it applies whatever durability you set it to.

 Also I noticed that a server ignores the config file and instead applies settings from the client config.

**Comment by CammiePone** [comment]
in the case of durability, it has to be the same on both the client and the server. durability of an item is set when the item is registered, meaning in order to change it on either side, you would need to restart the game

obviously because you cant restart the game when you join a server, the change needs to be made in both configs, else players will only ever see the change on their end causing weird bugs

**Comment by ItzLucaGER** [comment]
I see, thanks for clarifying :)
