### ISSUE TITLE
Icarus Wings not showing up on custom origin 

### ISSUE THREAD

**Issue by Trollkiss** [CammiePone/Icarus#49]
Hi, I'm trying to code a custom fruit bat origin for my server, but I can't seem to get it to work. I grabbed your icarae code (wings.json) and modified it slightly to have black dragon wings instead of the default, as well as not be as slowing with armor 
I tried looking in the logs but I can't seem to find any reason as to why it wouldn't. 

Hers my code for reference : 
```
{
    "name": "Small but Mighty",
    "description": "Even if your wings are small, you are capable of powered flight at low altitudes.",
    "type": "icarus:wings",
    "wings_type": "icarus:black_dragon_wings",
    "speed": 0.02,
    "armor_slow_multiplier": 1,
    "can_fly": true,
    "armor_slows": true
}
```

**Comment by CammiePone** [comment]
its a bug on my end, I have to fix it still. will be done as soon as I can get around to it

**Comment by muon-rw** [comment]
Until this is fixed you can modify the existing icarus wings power and give your origin that as a workaround, provided you don't mind also changing Icarae.

**Comment by SebbySaber** [comment]
It's still not working for me in 1.19.3 in the latest version of both mods

**Comment by CammiePone** [comment]
because I havent fixed it yet. the issue will be closed and you will be notified when it is fixed

**Comment by BaconPalm** [comment]
May I assume that this issue is still unresolved and the reason the origins features haven't been ported to the 1.20 version of the mod?

**Comment by deadman124** [comment]
so still not fixed i assume or something

**Comment by UpcraftLP** [comment]
Origins support will be moved to a separate mod.
