### ISSUE TITLE
Icarae is able to fly unrestricted

### ISSUE THREAD

**Issue by TheOdiumWitch** [CammiePone/Icarus#5]
With the latest version of icarus combined with the latest version of origins, on 1.18, it looks like the icarae origin is able to fly as long as they're within 50-75 blocks of solid ground, effectively giving them unrestricted powered flight.

**Comment by CammiePone** [comment]
It's 64, and yes. That is intentional

**Comment by TheOdiumWitch** [comment]
Ah, I didn't know that. Is there any chance the height could be made configurable?

**Comment by CammiePone** [comment]
It already is :p

**Comment by TheOdiumWitch** [comment]
I don't see that option :sweat_smile: 
Is it in the icarus.json5?
