### ISSUE TITLE
Cannot fly, not even glide anymore

### ISSUE THREAD

**Issue by ShieldMaidenVal** [CammiePone/Icarus#51]
I'm not sure what changed at all in my SP world, nothing added or options for Icarus changed save for the durability of them, and now back to the title. Any solutions? I'm rather attached to my wings!

**Comment by CammiePone** [comment]
duplicate of #42. please check issues before making new ones

**Comment by ShieldMaidenVal** [comment]
It's not a duplicate, as I cannot even glide at all either. I have zero functionality from the mod.
