### ISSUE TITLE
[request] and [bug] 1.19.4 support

### ISSUE THREAD

**Issue by Merith-TK** [CammiePone/Icarus#53]
So, I know the method in which I got this error is ***VERY OBVIOUSLY UNSUPPORTED***

but I said screw it and patched the mod.json file to run on 1.19.4 and... well...
this is it without the patch (and log)
![image](https://user-images.githubusercontent.com/10422110/231600666-1a120987-5ea9-47d7-8348-fa69e7424148.png)
https://mclo.gs/4AW8SsI

and with the "patch"
![image](https://user-images.githubusercontent.com/10422110/231601092-e4f118f9-92db-4154-9f95-dc0caafe940e.png)
https://mclo.gs/Ko3biRC

By far, the weirdest non-crash issue with a mod being forced to run on 1.19.4 when it only supports 1.19.3

**Comment by Merith-TK** [comment]
oh, and with the "patch" the "search items" tab is just *empty"

**Comment by UpcraftLP** [comment]
Sorry for the late reply, but at this point 1.19.x wont be officially supported anymore.
