### ISSUE TITLE
Client and server durability config syncing

### ISSUE THREAD

**Issue by KLONOA9X6** [CammiePone/Icarus#54]
As the title, Icarus mod can't sync the config between client and server, that caused if you set the durability on server and don't change client config, when durability is reduced to 1, the wings will still usable until the wings completely damage and disappear.

**Comment by CammiePone** [comment]
Minecraft and Icarus versions, please

**Comment by KLONOA9X6** [comment]
Minecraft: 1.19.2 (Fabric 0.14.19)
Icarus: https://github.com/KLONOA9X6/Icarus/commit/eca9397cea0c47754d9e5e31b3ff83b5f92f2444

**Comment by CammiePone** [comment]
this was fixed in 1.19.3 and it wont be backported, so uh... update i guess?

**Comment by KLONOA9X6** [comment]
It's impossible to upgrade minecraft server version to 1.19.3 because our server is using some mods that not release for 1.19.3 version (e.g. Create fabric version).

**Comment by KLONOA9X6** [comment]
Arr...I found it (Branch 1.19.2-suffering).
![image](https://user-images.githubusercontent.com/95112579/232963371-45644c0c-7c9c-4da9-9fe0-1428902ada11.png)
Looks like you made a mistake

**Comment by CammiePone** [comment]
durability is not something you can change on the fly. thats set during registry, and Mojang hasnt made items a dynamic registry. it would require a game restart to go into effect

**Comment by KLONOA9X6** [comment]
Arr... It looks a little difficult...
But I think this glitch is not only on 1.19.2 branch, but also on other branch...

**Comment by CammiePone** [comment]
its not a glitch, its technically impossible. even if I wanted to sync the durability, it *literally* cant be.

**Comment by KLONOA9X6** [comment]
I'm a little bit to describe the problems that may occur

Server config: 500 durability
Client config: 0 (infinity)

When damage value to 499, client will not stop flying, it will continue flying until the wing completely damaged and disappear.

**Comment by KLONOA9X6** [comment]
Well, forget it, I will build a separate version with modified durability values for the server to use

**Comment by CammiePone** [comment]
its literally not possible. an item's durability cant be changed while the game is running. what do you not understand about that

**Comment by KLONOA9X6** [comment]
I know, I did before and I know that's impossible
