### ISSUE TITLE
1.19.2 Allways flying, not landing anymore Bug

### ISSUE THREAD

**Issue by suerion** [CammiePone/Icarus#55]
Hey, we got an issue with the icarus mod.

-> https://clips.twitch.tv/BreakableTardyPangolinMVGame-MeZTLQQNiU37LVho

https://clips.twitch.tv/UgliestHappyWatermelonMingLee-2_v9Fwb5L1s21x7v

**Comment by CammiePone** [comment]
that's a vanilla problem, usually occurs when the server is lagging. if it's not that, try updating your Fabric API. I dont handle the landing code so there's nothing I can do

if the issue persists after that, report it to Fabric API since it uses their API
