### ISSUE TITLE
Problème de lancement du mod

### ISSUE THREAD

**Issue by LaPeTiTePaTaTeF** [CammiePone/Icarus#56]
Bonjour, 
J'ai un problème de lancement du mod, en fait, lorsque je lance Minecraft, il ne détecte même pas le mod, comme s'il n'existait pas. Il n'y a pas de message d'erreur, rien.
Pouvez vous m'aider ??

**Comment by LaPeTiTePaTaTeF** [comment]
Excusez-moi, je suis nouveau, donc je ne suis pas très au point, je n'étais pas sûr que cela corresponde au mod que je souhaitait.

Je parle du mod "Icarus", et j'aurais aimé retrouver une pair d'ailes dans mon Minecraft !!!

**Comment by CammiePone** [comment]
uhh... no habla Françoise?

**Comment by CammiePone** [comment]
Im sorry dude, I dont speak French. Im unfortunately monolingual and English is all I know. And even that I'm barely good with

**Comment by CammiePone** [comment]
Uhhh vous avez le bon mod, mais je ne sais pas vraiment ce qui cause votre problème. J'utilise Google Translate donc j'espère vraiment que cela se passera correctement.

**Comment by LaPeTiTePaTaTeF** [comment]
Oui, j'ai le bon mod, ne vous inquiétiez pas.
Désolé, moi non plus, je ne parle pas trop l'anglais, mais je pense qu'on pourrait y arriver.

**Comment by Xiribidus** [comment]
They are probably using forge

**Comment by LaPeTiTePaTaTeF** [comment]
En effet, j'utilise le site curseforge pour installer tous mes mods et généralement, tout se passe comme prévu, sauf pour ce mod là.

https://www.curseforge.com/minecraft/mc-mods/icarus/files

Voici le lien du site.

J'ai testé ce mod en 1.19 et en 1.19.3.

**Comment by Xiribidus** [comment]
Essaye utiliser [fabric](https://fabricmc.net/use/installer/), ce mod ne va pas fonctionner avec forge.

Curseforge n'est pas la même chose comme forge, forge et fabric sont méthodes différentes pour charger les mods, curseforge est pour les télécharger. (Mais curseforge peut être utilisé pour les charger aussi, dans ce case change le modpack de forge à fabric.)

**Comment by LaPeTiTePaTaTeF** [comment]
Merci, c'était cela, je n'avais jamais rencontré ce problème auparavant.

Merci beaucoup !!

N'y aurait-il pas un moyen de le transférer de fabric à forge ??
Mon idée était de jouer avec quelque mods, et je pensais que ce serait une bonne idée d'ajouter des ailes.
