### ISSUE TITLE
[Request] Configurable Flight Height

### ISSUE THREAD

**Issue by Nillo-Code** [CammiePone/Icarus#57]
I'd like to be able to configure the height at which a player can gain speed when flying, by modifying this `64` value here with a new key value pair in the config file.

https://github.com/CammiePone/Icarus/blob/a4686a51489c435dc29dbd2188109305f73c2661/src/main/java/dev/cammiescorner/icarus/core/mixins/PlayerEntityMixin.java#L34-L35

**Comment by CammiePone** [comment]
yea, i can add that
