### ISSUE TITLE
Server config not updating from icarus.json changes

### ISSUE THREAD

**Issue by anonlurker** [CammiePone/Icarus#59]
I'm running a Fabric 1.19.2 multiplayer server with the Fabric Medieval Minecraft Modpack (MMC1) which contains this mod. My friends and I wanted to update the config to disable the armor slow and allow sneaking midflight, but updating the config/icarus.json file to contain these settings
```
  "armourSlows": false,
  "canSlowFall": true,
  "maxSlowedMultiplier": 0.0,
```
and restarting the server didn't seem to work - syncing the values with the clients did not work either. Editing the origins config on the other hand correctly updated the features that the mod allowed, such as enabling/disabling shield usage. Could I check if I am doing something wrongly?

Thanks!

**Comment by CammiePone** [comment]
whats your version of Icarus?

**Comment by anonlurker** [comment]
Its 1.14

**Comment by anonlurker** [comment]
would it work if i recompiled the jar from the v1.14 release with new defaults in IcarusConfig?

I see theres an open issue on https://github.com/TeamMidnightDust/MidnightLib/issues/29 which hints it may not work with loading server configs
