### ISSUE TITLE
Suggestion: Keep wings but drop inventory

### ISSUE THREAD

**Issue by RunawayCobra** [CammiePone/Icarus#62]
It would be good if there could be an option on world creation, such as  "Keep wings but drop inventory". It can be really frustrating, especially on roleplay or SMP servers where your character canonically has wings, but if you die, the wings drop off. If there could be an extra option, then SMPs can still drop inventory like normal, but your character's wings can still stay in the Cape Trinket slot

**Comment by UpcraftLP** [comment]
This can be better solved with dedicated mods, for example the [Soulbound](https://modrinth.com/mod/soulbound) enchantment, or the origins companion mod for icarus that will soon be released (Then you can just create a custom origin that has wings as one of their powers).
