### ISSUE TITLE
Issue #29 is back

### ISSUE THREAD

**Issue by ARoyalPain** [CammiePone/Icarus#64]
The same exact thing that was happening in Issue #29 is back for me. This is happening in the latest release of the mod version 1.20.1. Im not sure if its another mod interfering or that same issue with the  WingItem#isUsable boolean being set at 0.

**Comment by JedGITH** [comment]
If in creative, change to survival and eat something to remove hunger, and then go back into creative should fix your issue. If you have this issue with full hunger and in survival than different story.
