### ISSUE TITLE
Icarus not showing in Origin selection menu

### ISSUE THREAD

**Issue by MoJo4000** [CammiePone/Icarus#67]
What the title says, Icarus isn't showing in the menu but the mod is installed. 

Sorry, I don't know how to label Github comments.

**Comment by muon-rw** [comment]
Origins features weren’t ported to 1.20+

**Comment by Kereswedhen** [comment]
> Origins features weren’t ported to 1.20+

How come?

**Comment by muon-rw** [comment]
> > Origins features weren’t ported to 1.20+
> 
> How come?

Setting up and maintaining an Origins Development environment has always been a bit of a nightmare, and the Icarus dev didn’t want to keep dealing with it. 

Happens

**Comment by Hyxth** [comment]
Massive L. should add it to origins.

**Comment by Xamos** [comment]
Yeah not using this until Icarus comes back into Origins :/ That was the ONLY origin I used lol.

**Comment by CammiePone** [comment]
I don't get paid enough to maintain Origins support.

The Icarae Origin was fun, don't get me wrong. It's all I ever used too, but it was actually detrimental to my mental health every single update to fix it just so it maybe works and has 20+ new bugs because Origins changed something and didn't document it.

People complain about Mojang changing a bunch of things each update - now imagine a team of programmers with no coordination doing the same thing every time they update to a new minor version. That's what it felt like trying to maintain support for Origins. At some point, it's just not worth my time and stress to make it happen, because it can take multiple days just to get it semi-functional - at which point dozens of new bugs are likely introduced, either in Origins itself that I take the blame for, or in Icarus itself because Origins never documented their stuff properly and thus I did something wrong.

**Comment by Xamos** [comment]
> I don't get paid enough to maintain Origins support.
> 
> The Icarae Origin was fun, don't get me wrong. It's all I ever used too, but it was actually detrimental to my mental health every single update to fix it just so it maybe works and has 20+ new bugs because Origins changed something and didn't document it.
> 
> People complain about Mojang changing a bunch of things each update - now imagine a team of programmers with no coordination doing the same thing every time they update to a new minor version. That's what it felt like trying to maintain support for Origins. At some point, it's just not worth my time and stress to make it happen, because it can take multiple days just to get it semi-functional - at which point dozens of new bugs are likely introduced, either in Origins itself that I take the blame for, or in Icarus itself because Origins never documented their stuff properly and thus I did something wrong.

I never realized it was that much work. Must be a lot more it it, I was just adding elytrian wings power to a custom origin now to see what that's like.

Do I get the same functionality just using the icarus wings?

**Comment by Hyxth** [comment]
> > I don't get paid enough to maintain Origins support.
> > The Icarae Origin was fun, don't get me wrong. It's all I ever used too, but it was actually detrimental to my mental health every single update to fix it just so it maybe works and has 20+ new bugs because Origins changed something and didn't document it.
> > People complain about Mojang changing a bunch of things each update - now imagine a team of programmers with no coordination doing the same thing every time they update to a new minor version. That's what it felt like trying to maintain support for Origins. At some point, it's just not worth my time and stress to make it happen, because it can take multiple days just to get it semi-functional - at which point dozens of new bugs are likely introduced, either in Origins itself that I take the blame for, or in Icarus itself because Origins never documented their stuff properly and thus I did something wrong.
> 
> I never realized it was that much work. Must be a lot more it it, I was just adding elytrian wings power to a custom origin now to see what that's like.
> 
> Do I get the same functionality just using the icarus wings?

The Icarus mod itself still gives you access to the wings you need for the flight functionality, and as far as i've been able to test them in 1.20.1 for the few minutes that i did, they seem to work just fine. I spawn in as an avian using the origins mod, and then go into creative and give myself my preferred wings. after i do that i utilize an enchanted book called "soulbound" that you get from a mod called "You're in Grave Danger". use an anvil to bind a souldbound book to the icarus wings and now you've got yourself a frankensteined icarus origin with avian traits. sadly all of this would require you to have someone or yourself go into creative mode (assuming you have "you're in grave danger" mod.) and make you a soulbound pair of wings. also you have the traits of an avian which isn't quite like what icaruses meat-only, and fragile-bodied nature that it normally comes with, but it's the best i could come up with being a non-modder.
