### ISSUE TITLE
Issue with flying

### ISSUE THREAD

**Issue by BloodKneight** [CammiePone/Icarus#73]
I was able fly without issues now it this weird slow flight almost like a gliding flight. I can only fly in loops, difficult get off ground, or make any hard turn. I also can't slow down and it impossible to land? I this a toggle that I can turn off.

**Comment by JedGITH** [comment]
Check your mod pack, and remove the mod 'do a barrel roll,' this mod changes the normal elytra flight to a more 'realistic' feel, removing it fixes the gliding issue.

**Comment by UpcraftLP** [comment]
duplicate of #42
