### ISSUE TITLE
mod not loading

### ISSUE THREAD

**Issue by DanTheJollyMan** [CammiePone/Icarus#79]
i've downloaded the mod and all its dependencies, but it won't load.
tried different forge versions too, still no results

**Comment by CammiePone** [comment]
its not a Forge mod ^^;

**Comment by DanTheJollyMan** [comment]
is there any way to get it to work with forge?

**Comment by CammiePone** [comment]
no, its made for Fabric, a completely separate modloader. there may be a neoforge version made in the future, but at the moment it only runs on Fabric
