### ISSUE TITLE
Minecraft Crashes

### ISSUE THREAD

**Issue by Ivan-Draws** [CammiePone/Icarus#8]
Hi! 
I've been meaning to make this message for a while but I always forget.

Every time I even try to load up the game from the launcher it crashes before the game loads. It keeps saying it is due to this mod and I don't really know why. I believe I have everything the mod needs, but it decides it doesn't wish to be compatible with my laptop.

I believe I can send you the crash report it sent if that helps!

I really want to play with this mod and witness all the pretty wings!

Ps: Crash Report 

[Crash Report Icarus.txt](https://github.com/CammiePone/Icarus/files/7698141/Crash.Report.Icarus.txt)

**Comment by CammiePone** [comment]
Update Fabric API
