### ISSUE TITLE
Tag location for datapack?

### ISSUE THREAD

**Issue by Shadowblitz0001** [CammiePone/Icarus#82]
The curseforge page says that there's a tag that lets it be added to a datapack so the wings won't consume hunger. Where is that/ how do I do that?

**Comment by UpcraftLP** [comment]
any wings that are in the [`icarus:free_flight`](https://github.com/Up-Mods/Icarus/blob/c8c85845e021127d8fb46f92af16667a7d71bce4/Common/src/main/resources/data/icarus/tags/items/free_flight.json) tag wont consume hunger. You can find more info about tags on the [Minecraft Wiki](https://minecraft.wiki/w/Tag)
