### ISSUE TITLE
Crash on modloading with (Neo)Forge version 2.0.1

### ISSUE THREAD

**Issue by PinkLasagna03** [CammiePone/Icarus#83]
Only JEI, JADE and the mod with dependencies were installed on Forge 1.20.1 and version 47.2.20

[latest.log](https://github.com/Up-Mods/Icarus/files/14970506/latest.log)

**Comment by UpcraftLP** [comment]
Yeah I've already noticed, somehow the file doesnt export correctly. will be fixed soon™

**Comment by PinkLasagna03** [comment]
It indeed still gives the crash after the update
[latest.log](https://github.com/Up-Mods/Icarus/files/14971188/latest.log)

**Comment by UpcraftLP** [comment]
Yeah, something broke with mixins and I haven't yet figured out what.
And it seems to be affecting ALL the files

**Comment by UpcraftLP** [comment]
ok this one is fixed in v2.1.1, gonna work on the fabric one next ^^

**Comment by UpcraftLP** [comment]
*2.1.3, had some other issues with publishing still

**Comment by PinkLasagna03** [comment]
> Yeah, something broke with mixins and I haven't yet figured out what. And it seems to be affecting ALL the files


Damnnn, pretty nice you're working on it tho :)

**Comment by Kaede4Life** [comment]
still seems to crash early on for me

[latest.log](https://github.com/Up-Mods/Icarus/files/14971946/latest.log)

**Comment by UpcraftLP** [comment]
> still seems to crash early on for me
> 
> [latest.log](https://github.com/Up-Mods/Icarus/files/14971946/latest.log)

That's a mod conflict, not related to this issue.
regardless, I published a fix for it.
