### ISSUE TITLE
Can't join singleplayer world on Fabric 

### ISSUE THREAD

**Issue by PinkLasagna03** [CammiePone/Icarus#84]
Only dependencies, v2.1.0 of the mod. Fabric 0.15.10 on 1.20.1

[latest.log](https://github.com/Up-Mods/Icarus/files/14971200/latest.log)

**Comment by UpcraftLP** [comment]
This is an issue with Common Networking, will be fixed on their end soon.

Tracking issue:
https://github.com/mysticdrew/common-networking/issues/4

**Comment by UpcraftLP** [comment]
Fixed upstream, updating Common Network will resolve this issue.
