### ISSUE TITLE
Issues with the 1.20.1 forge version

### ISSUE THREAD

**Issue by Greg727** [CammiePone/Icarus#85]
Quick question, is this just supposed to be for NeoForge or can it be done through regular forge to? If not, then using it on forge is probably the issue.

But if it can be done then I'm still receiving crashes whenever I try to start the game

Mod Version: 2.1.3+Neo Forge
Forge Version: 47.2.23

**Comment by UpcraftLP** [comment]
In 1.20.1, Forge and NeoForge are basically identical, therefore neoforge mods will work on forge (and I tested that Icarus works).

If you still have crashes, please provide a log ^^

**Comment by Greg727** [comment]
From what I've gathered it works fine if it's just the mod and it's required dependencies by themselves, but it will not work if there are other mods installed,

Also I want to give it a log, but it's one of those crashes that don't make one.

**Comment by UpcraftLP** [comment]
Show it anyway

**Comment by Greg727** [comment]
No need, whatever you did you fixed it, thank you

**Comment by laneyfamily** [comment]
I'm getting a crash on 1.20.1 forge version 47.2.23
Icarus version 2.1.4

[crash-2024-02-22_21.40.45-client.txt](https://github.com/Up-Mods/Icarus/files/14972604/crash-2024-02-22_21.40.45-client.txt)

**Comment by UpcraftLP** [comment]
> I'm getting a crash on 1.20.1 forge version 47.2.23 Icarus version 2.1.4
> 
> [crash-2024-02-22_21.40.45-client.txt](https://github.com/Up-Mods/Icarus/files/14972604/crash-2024-02-22_21.40.45-client.txt)

Your modpack does not even seem to include icarus? At least that crash log doesn't.
If you are experiencing issues with icarus, open a new issue and provide a relevant log file.
