### ISSUE TITLE
Another crash with forge 1.20.1 latest version

### ISSUE THREAD

**Issue by PinkLasagna03** [CammiePone/Icarus#86]
[latest.log](https://github.com/Up-Mods/Icarus/files/14972047/latest.log)
[crash-2024-04-14_22.36.37-client.txt](https://github.com/Up-Mods/Icarus/files/14972048/crash-2024-04-14_22.36.37-client.txt)

**Comment by UpcraftLP** [comment]
Update curios

**Comment by PinkLasagna03** [comment]
> Update curios

that works, since the newest version of curios is a beta it doenst show up as needed to update
