### ISSUE TITLE
Crashing Upon Loading into Single Player World

### ISSUE THREAD

**Issue by LadyDelyria** [CammiePone/Icarus#87]
Hi! I'm not very good at reading crash logs so I'm not sure what's going on. Every time I go to load into a single player world, my game crashes. It only happens whenever I have this mod installed so I know it's the issues but I'm not sure how to go about fixing it. 
[crash-2024-04-14_18.57.12-client.txt](https://github.com/Up-Mods/Icarus/files/14972413/crash-2024-04-14_18.57.12-client.txt)

**Comment by LadyDelyria** [comment]
Apparently I didn't have Curios installed but I swore I'd checked prior to installing Icarus and it was there? Oh well, haha. This is here if anyone else needs it

**Comment by UpcraftLP** [comment]
You probably had it, but a wrong version. Icarus requires some features that only exist in the beta versions, not in the latest release of curios.
