### ISSUE TITLE
[Bug] 🐞Crash At Loading World

### ISSUE THREAD

**Issue by serioos** [CammiePone/Icarus#89]
I generated a new world with Icarus installed and it crashed my game.

![2024-04-15_20 29 44](https://github.com/Up-Mods/Icarus/assets/93765296/671fefca-b411-47f3-9ed9-0c0616cf5179)

Here are the logs:

[crash-2024-04-15_20.29.35-client.txt](https://github.com/Up-Mods/Icarus/files/14982237/crash-2024-04-15_20.29.35-client.txt)

[latest.log](https://github.com/Up-Mods/Icarus/files/14982239/latest.log)

Minecraft 1.20.1 Forge - 47.2.20

Icarus-NeoForge-2.1.5.jar

**Comment by UpcraftLP** [comment]
Update curios to the latest version
