### ISSUE TITLE
Add config options to disable modifying the Origins mod and max height

### ISSUE THREAD

**Issue by ultimatejacob27** [CammiePone/Icarus#90]
When choosing the Elytrian in origins, it now has the ability to propel forward, despite only having elytra. If this is a feature, it would be nice if it could be disabled. Also, while the max height alludes to the story of Icarus, I would rather disable that feature.

**Comment by CammiePone** [comment]
@UpcraftLP i think you made another oops in the rewrite

also, if you want to disable the max height, just set it to something like 3 million
