### ISSUE TITLE
Flying into water with "do a barrel roll" installed crashes the game

### ISSUE THREAD

**Issue by AmazingGates96** [CammiePone/Icarus#91]
### When used with "Do a Barrel Roll" mod by enjarai, if you go in water while flying on a server, it crashes your game and you have to delete your character file to play again

I'm using the Prominence II modpack and have these two mods together, every time on my family server that someone enters the water (it seems to be only while flying, and only with the Icarus wings) they crash and the only way to play on the server again is if they delete their character file completely from the server PC. I don't have the crash log right now because my brother is the one who kept having this happen to him, and it's a pain to get everything back. If need be I can try to replicate it, but it's very annoying to deal with afterward and I'd like to avoid that until it's necessary. Seems to only happen in multiplayer, unsure if this applies to LAN at the moment.

**Comment by UpcraftLP** [comment]
A crash log would be very helpful

**Comment by UpcraftLP** [comment]
Fixed in `v2.5.0`, if you still get crashes with that version, feel free to re-open the issue ^^

**Comment by AmazingGates96** [comment]
This works for the LAN servers now, thank you!! I'll try the regular server later once my dad updates the modpack on the server computer.
