### ISSUE TITLE
Crash on startup: Epic Fight Mod

### ISSUE THREAD

**Issue by Aabaddon** [CammiePone/Icarus#94]
[crash-2024-04-30_18.24.04-client.txt](https://github.com/Up-Mods/Icarus/files/15172160/crash-2024-04-30_18.24.04-client.txt)

I dont kow what happens, it seems to be incompatible with every single mod i try to add to the modpack

**Comment by CammiePone** [comment]
can you post it in pastebin? im on mobile so i cant view txt files

**Comment by Aabaddon** [comment]
https://pastebin.com/z6M77qU9

**Comment by CammiePone** [comment]
hm. looks like something broke when compiling the mod with one of the mixins. whenever @UpcraftLP can get around to it, she'll likely be able to fix it

**Comment by Aabaddon** [comment]
i hope so :C i really love this mod

**Comment by UpcraftLP** [comment]
Hey, what version of Icarus are you using?
I just tested the latest one extensively, and it seems to work fine.

Also could you provide a mod list maybe?

**Comment by FuryJack07** [comment]
I get [this Crash report](https://pastebin.com/exA67nwF) on startup when trying to load this and the Epic fight mod.

**Comment by UpcraftLP** [comment]
> I get [this Crash report](https://pastebin.com/exA67nwF) on startup when trying to load this and the Epic fight mod.

working fine for me, so would you, too, please provide a full mod list, or a minimal reproduction case?

<Details>
<Summary>
Click to see attached screenshot
</Summary>

![image](https://github.com/Up-Mods/Icarus/assets/10714589/2cef68a8-bf82-4816-a110-f827e775432f)
</Details>

**Comment by FuryJack07** [comment]
Ok, now I am confused. it seems like having Epic fight and Icarus and the needed libraries loaded plus minecraft and forge counting as mods makes the number of loaded mods 9, then you can reach 25 mods loaded and it will work fine, meaning 16 more mods. add one more, and the game will crash. no matter what the 17 extra mods are. What in the actual fu-

**Comment by FuryJack07** [comment]
Doesn't matter what mods you use, the game WILL crash when you reach 26 total mods with Epic fight and Icarus.

**Comment by UpcraftLP** [comment]
I cant reproduce that happening, so I would really appreciate it if you could give me an exact list of mods + their versions that causes it.

**Comment by FuryJack07** [comment]
CurseForge, forge 47.2.30, minecraft 1.20.1 all latest versions for each mod [Pastebin link](https://pastebin.com/VimX68GD).
This is fine, but add one more mod, ANY mod and the game crashes

**Comment by CammiePone** [comment]
still would be appreciated if you gave us the exact versions of each mod. we've had people who believed they were on latest only for them to be several versions behind because CurseForge or Modrinth just didn't tell them there were new files

**Comment by FuryJack07** [comment]
ok... even though I doubt 
Caelus API 3.2.0
Common Network 1.0.3
Curios API 5.9.0
Epic fight 20.7.4
Icarus 2.7.1
Resourceful Config 2.1.2

these are the only needed mods, as you can use any other mod to contribute to the crash but here we go anyway

Epic Fight - Guandeo Moveset 20.6.1
Epic Fight Battle Styles 1.0.3
Epic Fight Mod & Other Mods Weapons Compabilities 2.0
Icarae Origin 1.0.0
Load My F***ing Tags 1.0.4 (Yes it's written like this, with the *)
Origins (Forge) 1.10.0.9
The Aether 1.4.2
Vampirism - Become a vampire! 1.10.7
Vampirism Integrations 1.8.0
Weapons of Miracles - epic fight 20.1.7.40

This is fine, but add any other mod like...
Vampiric Ageing - A Vampirism Addon 1.3.20
and the game will crash before it even begins.

I am on Windows 11 home version 23H2
Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz Processor, 
64 bit operating system and Processor and
Minecraft has 4 GB of RAM to use.
CurseForge Is on version 1.250.3.17797

This about everything I can give to you.

**Comment by CammiePone** [comment]
thank you 👍 
it does help a lot to know the exact versions of most everything, even if it seems like it shouldn't make much of a difference

**Comment by FuryJack07** [comment]
I may have gone overboard by also sharing system details but... who knows, such weird crash could be my pc's fault. I mean, the fact that it crashes when you add 17 mods REGARDLESS OF WHICH MODS YOU ADD is pretty weird

**Comment by FuryJack07** [comment]
Note, the Epic fight mod Is a pretty glitchy mod, and it has always been crashy and with weird crash reports, so I think it's that mod's fault, but you answered first sooo... Hopefully it can be fixed because they're both very fun mods.

**Comment by CammiePone** [comment]
okay I found the problem. In the current latest version of Epic Fight, they have a redirect that replaces the method we mixin into, adding a new variable as the first one. clearly not our fault, they should not be doing a redirect in the first place, nor should they be doing it unconditionally

the good news is when 20.7.5 comes out, it completely gets rid of that mixin so it should work going forward as long as they don't make any other silly changes. why it only happens with 26 or more mods, I have no idea, but at least we know the problem now

**Comment by FuryJack07** [comment]
YOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO YOU'RE INSAAAANE!!!!!!!!!!!!!!!!!! I LOVE YOU!!!!

Ahem. sorry, got exited. Thank you.
