### ISSUE TITLE
[Suggestion] Put older versions on Modrinth

### ISSUE THREAD

**Issue by GoldenFurredFox** [CammiePone/Icarus#98]
### Mod Loader

Fabric

### Minecraft Versions

1.16.3, 1.16.4, 1.18.1, 1.18.2, 1.19.1, 1.19.2

### Mod Versions

0.1, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 1.10, 1.11

### Suggestion

It'd improve my quality of life, and I'm sure the quality of life of many others, if you'd add the mod versions prior to Minecraft version 1.19 to your Modrinth release page for Icarus.

**Comment by UpcraftLP** [comment]
I've uploaded the latest 1.19.2 + 1.19.3/.4 versions, the rest I wont bother with as (almost) nobody plays those versions anymore, and those that do can just get the mod from Curseforge instead.

That said, anything before 1.20.1 is unsupported regardless.
